In [2]:
import datetime
from pandas_datareader import data
from bokeh.plotting import figure, show, output_file

start_date = datetime.datetime(2020,5,1)
end_date = datetime.datetime(2020,5,22)

df = data.DataReader(name="GOOG",data_source="yahoo",start=start_date,end=end_date)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2668900,1348.660034
2020-05-01,1352.069946,1311.000000,1328.500000,1320.609985,2072500,1320.609985
2020-05-04,1327.660034,1299.000000,1308.229980,1326.800049,1504000,1326.800049
2020-05-05,1373.939941,1337.459961,1337.920044,1351.109985,1651500,1351.109985
2020-05-06,1371.119995,1347.290039,1361.689941,1347.300049,1215400,1347.300049
2020-05-07,1377.599976,1355.270020,1365.939941,1372.560059,1397600,1372.560059
2020-05-08,1398.760010,1375.479980,1383.130005,1388.369995,1388100,1388.369995
2020-05-11,1416.530029,1377.151978,1378.280029,1403.260010,1410600,1403.260010
2020-05-12,1415.000000,1374.770020,1407.119995,1375.739990,1390600,1375.739990
2020-05-13,1385.482056,1328.400024,1377.050049,1349.329956,1812600,1349.329956
2020-05-14,1357.420044,1323.910034,1335.020020,1356.130005,1603100,1356.130005
2020-05-15,1374.479980,1339.000000,1350.000000,1373.189941,1707700,1373.189941
2020-05-18,1392.324951,1354.250000,1361.750000,1383.939941,1824000,1383.939941
2020-05-19,1392.000000,1373.484985,1386.996948,1373.484985,1280600,1373.484985
2020-05-20,1410.420044,1387.250000,1389.579956,1406.719971,1655400,1406.719971
2020-05-21,1415.489990,1393.449951,1408.000000,1402.800049,1385000,1402.800049

In [4]:
date_increase = df.index[df.Close > df.Open]
date_decrease = df.index[df.Close < df.Open]

In [6]:
def inc_dec(c,o):
    if c > o:
        value = "Increase"
    elif c < o:
        value = "Decrease"
    else:
        value = "equal"
    return value    
        
df["Status"] = [inc_dec(c,o) for c,o in zip(df.Close,df.Open)]
df

,High,Low,Open,Close,Volume,Adj Close,Status
Date,,,,,,,
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2668900,1348.660034,Increase
2020-05-01,1352.069946,1311.000000,1328.500000,1320.609985,2072500,1320.609985,Decrease
2020-05-04,1327.660034,1299.000000,1308.229980,1326.800049,1504000,1326.800049,Increase
2020-05-05,1373.939941,1337.459961,1337.920044,1351.109985,1651500,1351.109985,Increase
2020-05-06,1371.119995,1347.290039,1361.689941,1347.300049,1215400,1347.300049,Decrease
2020-05-07,1377.599976,1355.270020,1365.939941,1372.560059,1397600,1372.560059,Increase
2020-05-08,1398.760010,1375.479980,1383.130005,1388.369995,1388100,1388.369995,Increase
2020-05-11,1416.530029,1377.151978,1378.280029,1403.260010,1410600,1403.260010,Increase
2020-05-12,1415.000000,1374.770020,1407.119995,1375.739990,1390600,1375.739990,Decrease
2020-05-13,1385.482056,1328.400024,1377.050049,1349.329956,1812600,1349.329956,Decrease
2020-05-14,1357.420044,1323.910034,1335.020020,1356.130005,1603100,1356.130005,Increase
2020-05-15,1374.479980,1339.000000,1350.000000,1373.189941,1707700,1373.189941,Increase
2020-05-18,1392.324951,1354.250000,1361.750000,1383.939941,1824000,1383.939941,Increase
2020-05-19,1392.000000,1373.484985,1386.996948,1373.484985,1280600,1373.484985,Decrease
2020-05-20,1410.420044,1387.250000,1389.579956,1406.719971,1655400,1406.719971,Increase
2020-05-21,1415.489990,1393.449951,1408.000000,1402.800049,1385000,1402.800049,Decrease

In [7]:
df["Middle"] = (df.Open + df.Close)/2
df["Height"] = abs(df.Close - df.Open)
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2020-04-30,1352.819946,1322.489990,1324.880005,1348.660034,2668900,1348.660034,Increase,1336.770020,23.780029
2020-05-01,1352.069946,1311.000000,1328.500000,1320.609985,2072500,1320.609985,Decrease,1324.554993,7.890015
2020-05-04,1327.660034,1299.000000,1308.229980,1326.800049,1504000,1326.800049,Increase,1317.515015,18.570068
2020-05-05,1373.939941,1337.459961,1337.920044,1351.109985,1651500,1351.109985,Increase,1344.515015,13.189941
2020-05-06,1371.119995,1347.290039,1361.689941,1347.300049,1215400,1347.300049,Decrease,1354.494995,14.389893
2020-05-07,1377.599976,1355.270020,1365.939941,1372.560059,1397600,1372.560059,Increase,1369.250000,6.620117
2020-05-08,1398.760010,1375.479980,1383.130005,1388.369995,1388100,1388.369995,Increase,1385.750000,5.239990
2020-05-11,1416.530029,1377.151978,1378.280029,1403.260010,1410600,1403.260010,Increase,1390.770020,24.979980
2020-05-12,1415.000000,1374.770020,1407.119995,1375.739990,1390600,1375.739990,Decrease,1391.429993,31.380005
2020-05-13,1385.482056,1328.400024,1377.050049,1349.329956,1812600,1349.329956,Decrease,1363.190002,27.720093
2020-05-14,1357.420044,1323.910034,1335.020020,1356.130005,1603100,1356.130005,Increase,1345.575012,21.109985
2020-05-15,1374.479980,1339.000000,1350.000000,1373.189941,1707700,1373.189941,Increase,1361.594971,23.189941
2020-05-18,1392.324951,1354.250000,1361.750000,1383.939941,1824000,1383.939941,Increase,1372.844971,22.189941
2020-05-19,1392.000000,1373.484985,1386.996948,1373.484985,1280600,1373.484985,Decrease,1380.240967,13.511963
2020-05-20,1410.420044,1387.250000,1389.579956,1406.719971,1655400,1406.719971,Increase,1398.149963,17.140015
2020-05-21,1415.489990,1393.449951,1408.000000,1402.800049,1385000,1402.800049,Decrease,1405.400024,5.199951

In [8]:
p = figure(x_axis_type='datetime', width=1000, height=300, sizing_mode="scale_width")
p.title.text = "StockAnalysisGraph"
p.grid.grid_line_alpha=0.3

#p.segment(x val of highest pt,y val of highest pt,x val for lower pt,y val for lower pt)
p.segment(df.index, df.High, df.index, df.Low, color="black")

#p.rect(x coordinate,central y coordinate(centre of rect),width of rect(12 hrs into milisec),height of rect(diff bet open and close val))
hours_12 = 12*60*60*1000

p.rect(df.index[df.Status=="Increase"], df.Middle[df.Status=="Increase"],hours_12,df.Height[df.Status=="Increase"],
       fill_color="#00ab00",line_color="black")

p.rect(df.index[df.Status=="Decrease"], df.Middle[df.Status=="Decrease"],hours_12,df.Height[df.Status=="Decrease"],
       fill_color="#de0000",line_color="black")

output_file("trial.html")
show(p)